feat - add healthchecks to all services

diff --git a/.github/workflows/ui-tests-ci.yml b/.github/workflows/ui-tests-ci.yml
--- a/.github/workflows/ui-tests-ci.yml
+++ b/.github/workflows/ui-tests-ci.yml
@@ -105,7 +105,61 @@ jobs:
           SPRING_PROFILES_ACTIVE: SIT
         working-directory: backend
 
-      - name: Wait for application to be ready
+      - name: Wait for Discovery Service to be ready
+        timeout-minutes: 2
+        env:
+          HEALTHCHECK_URL: http://localhost:8761/actuator/health
+        run: |
+          ATTEMPT=1
+          
+          while true; do
+            echo "Attempt #$ATTEMPT: Checking health endpoint at $HEALTHCHECK_URL..."
+          
+            RESPONSE=$(curl -s $HEALTHCHECK_URL || true)
+            echo "$RESPONSE"
+          
+            if echo "$RESPONSE" | grep -q '"status":"UP"'; then
+              echo "Service is up and healthy! Health check passed."
+              exit 0
+            else
+              echo "Service is not available yet. Waiting 10 seconds before the next attempt..."
+              sleep 10
+            fi
+          
+            ATTEMPT=$((ATTEMPT + 1))
+          done
+          
+          echo "Health check failed to pass within the timeout period."
+          exit 1
+
+      - name: Wait for API Gateway Service to be ready
+        timeout-minutes: 2
+        env:
+          HEALTHCHECK_URL: http://localhost:8080/actuator/health
+        run: |
+          ATTEMPT=1
+          
+          while true; do
+            echo "Attempt #$ATTEMPT: Checking health endpoint at $HEALTHCHECK_URL..."
+          
+            RESPONSE=$(curl -s $HEALTHCHECK_URL || true)
+            echo "$RESPONSE"
+          
+            if echo "$RESPONSE" | grep -q '"status":"UP"'; then
+              echo "Service is up and healthy! Health check passed."
+              exit 0
+            else
+              echo "Service is not available yet. Waiting 10 seconds before the next attempt..."
+              sleep 10
+            fi
+          
+            ATTEMPT=$((ATTEMPT + 1))
+          done
+          
+          echo "Health check failed to pass within the timeout period."
+          exit 1
+
+      - name: Wait for Authorization Service to be ready
         timeout-minutes: 2
         env:
           HEALTHCHECK_URL: http://localhost:8081/actuator/health
